baseurl = "https://www.timlrx.com/"
publishDir = "./public"
relativeurls = false
languageCode = "en-us"
title = "Quasilinear Musings"
theme = "beautifulhugo"
googleAnalytics = "UA-100201704-1"
disqusShortname = ""
ignoreFiles = ["\\.Rmd$", "\\.Rkmd$", "\\.Rmarkdown$",  "_files$", "_cache$"]

[permalinks]
    post = "/:year/:month/:day/:slug/"

[[menu.main]]
    name = "Blog"
    url = "/post/"
    weight = 1
[[menu.main]]
    name = "About"
    url = "/about/"
    weight = 2
[[menu.main]]
    name = "SG-Dashboard"
    url = "dashboard/sg-dashboard/"
    weight = 3
[[menu.main]]
    name = "Resources"
    url = "/resources/"
    weight = 4
[[menu.main]]
    name = "Tags"
    url = "tags"
    weight = 5

[params]
  subtitle = "Thoughts from a wandering mind"
  rss = true

[Author]
  name = "Timothy Lin"
  email = "timothy.lin@alumni.ubc.ca"
  github = "timlrx"
  linkedin = "timothy-lin-0600ba141"
